QT += core gui opengl
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
TARGET = openscam
TEMPLATE = app
SOURCES += main.cpp ../src/openscam/qt/QtApp.cpp GLWidget.cpp
HEADERS += ../src/openscam/qt/QtApp.h GLWidget.h
FORMS += openscam.ui
RESOURCES += openscam.qrc
INCLUDEPATH += $$PWD/../src
DEPENDPATH += $$PWD/../src
