name: Build CAMotics Win

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_win:
    runs-on:  windows-2019

    env:
      SOURCE_DIR:   ${{ github.workspace }}
      QT_VERSION:   5.15.2
      ARTIFACT:     CAMotics

    defaults:
      run:
        #shell: cmd
        shell: powershell

    steps:
      - name: Install NSIS
        run: |
          curl.exe -L -O http://prdownloads.sourceforge.net/nsis/nsis-3.01-setup.exe
          ./nsis-3.01-setup.exe

      - name: Install Python
        run: |
          curl.exe -L -O https://www.python.org/ftp/python/2.7.12/python-2.7.12.amd64.msi
          ./python-2.7.12.amd64.msi /passive
          Remove-Item ./python-2.7.12.amd64.msi -Force

      - name: Install SCons
        run: |
          python.exe -m pip install --user scons

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get all tags for correct version determination
        working-directory:  ${{ github.workspace }}
        run: |
          git fetch --all --tags -f
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version:      ${{ env.QT_VERSION }}
          host:         windows
          target:       desktop
          arch:         win64_msvc2019_64
          dir:          ${{ runner.temp }}  
          setup-python: false

      - name: Download JOM
        uses: suisei-cn/actions-download-file@master
        with:
          url:    http://download.qt.io/official_releases/jom/jom.zip
          target: ${{ runner.temp }}\

      - name: Unzip JOM
        working-directory: ${{ runner.temp }}
        run:  |
              7z x jom.zip -ojom
              
      - name: Create build directory
        run:  mkdir ${{ runner.temp }}\build

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64
